### ISSUE TITLE
Help in porting NT APIs 

### ISSUE THREAD

**Issue by muhyuddin** [Nariod/RustPacker#23]
Hey Nariod,
Do have any guide/idea of porting different APIs to be used with compatible paramters? I am using [rust_syscalls](https://github.com/janoglezcampos/rust_syscalls/) in one of my projects. I have seen your issue there regarding same problem of using NtCreateThreadEx. I am looking for ways to use right types of args in function calls, i see you have achieved that in your project. 

Thankyou.

**Comment by Nariod** [comment]
Hi,

Yes I get the idea.. it is the main difficulty in writing offensive tooling in Rust. I don't have any specific guide or methodology, it is a trial and error process. You can have a look at https://github.com/BlWasp/rs-shell for syscall implementation examples.

All the best,
Nariod
